// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB140RkQcA2eKLs58sFD-rCvZJt4LAAZI8',
    appId: '1:930910441824:web:d6552fc70ee56a34ccce05',
    messagingSenderId: '930910441824',
    projectId: 'pulse-52aa3',
    authDomain: 'pulse-52aa3.firebaseapp.com',
    storageBucket: 'pulse-52aa3.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB140RkQcA2eKLs58sFD-rCvZJt4LAAZI8',
    appId: '1:930910441824:android:d6552fc70ee56a34ccce05',
    messagingSenderId: '930910441824',
    projectId: 'pulse-52aa3',
    storageBucket: 'pulse-52aa3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB140RkQcA2eKLs58sFD-rCvZJt4LAAZI8',
    appId: '1:930910441824:ios:d6552fc70ee56a34ccce05',
    messagingSenderId: '930910441824',
    projectId: 'pulse-52aa3',
    storageBucket: 'pulse-52aa3.firebasestorage.app',
    iosBundleId: 'com.pulse.consumer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB140RkQcA2eKLs58sFD-rCvZJt4LAAZI8',
    appId: '1:930910441824:ios:d6552fc70ee56a34ccce05',
    messagingSenderId: '930910441824',
    projectId: 'pulse-52aa3',
    storageBucket: 'pulse-52aa3.firebasestorage.app',
    iosBundleId: 'com.pulse.consumer',
  );
}